// Code generated by mockery. DO NOT EDIT.

package commandsmocks

import (
	context "context"
	commands "delivery/internal/core/application/usecases/commands"

	mock "github.com/stretchr/testify/mock"
)

// CreateOrderCommandHandlerMock is an autogenerated mock type for the CreateOrderCommandHandler type
type CreateOrderCommandHandlerMock struct {
	mock.Mock
}

type CreateOrderCommandHandlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CreateOrderCommandHandlerMock) EXPECT() *CreateOrderCommandHandlerMock_Expecter {
	return &CreateOrderCommandHandlerMock_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: _a0, _a1
func (_m *CreateOrderCommandHandlerMock) Handle(_a0 context.Context, _a1 commands.CreateOrderCommand) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CreateOrderCommand) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateOrderCommandHandlerMock_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type CreateOrderCommandHandlerMock_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 commands.CreateOrderCommand
func (_e *CreateOrderCommandHandlerMock_Expecter) Handle(_a0 interface{}, _a1 interface{}) *CreateOrderCommandHandlerMock_Handle_Call {
	return &CreateOrderCommandHandlerMock_Handle_Call{Call: _e.mock.On("Handle", _a0, _a1)}
}

func (_c *CreateOrderCommandHandlerMock_Handle_Call) Run(run func(_a0 context.Context, _a1 commands.CreateOrderCommand)) *CreateOrderCommandHandlerMock_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.CreateOrderCommand))
	})
	return _c
}

func (_c *CreateOrderCommandHandlerMock_Handle_Call) Return(_a0 error) *CreateOrderCommandHandlerMock_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CreateOrderCommandHandlerMock_Handle_Call) RunAndReturn(run func(context.Context, commands.CreateOrderCommand) error) *CreateOrderCommandHandlerMock_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewCreateOrderCommandHandlerMock creates a new instance of CreateOrderCommandHandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateOrderCommandHandlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateOrderCommandHandlerMock {
	mock := &CreateOrderCommandHandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
