// Code generated by mockery. DO NOT EDIT.

package portsmocks

import (
	context "context"
	courier "delivery/internal/core/domain/model/courier"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// CourierRepositoryMock is an autogenerated mock type for the CourierRepository type
type CourierRepositoryMock struct {
	mock.Mock
}

type CourierRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CourierRepositoryMock) EXPECT() *CourierRepositoryMock_Expecter {
	return &CourierRepositoryMock_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, aggregate
func (_m *CourierRepositoryMock) Add(ctx context.Context, aggregate *courier.Courier) error {
	ret := _m.Called(ctx, aggregate)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *courier.Courier) error); ok {
		r0 = rf(ctx, aggregate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CourierRepositoryMock_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type CourierRepositoryMock_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - aggregate *courier.Courier
func (_e *CourierRepositoryMock_Expecter) Add(ctx interface{}, aggregate interface{}) *CourierRepositoryMock_Add_Call {
	return &CourierRepositoryMock_Add_Call{Call: _e.mock.On("Add", ctx, aggregate)}
}

func (_c *CourierRepositoryMock_Add_Call) Run(run func(ctx context.Context, aggregate *courier.Courier)) *CourierRepositoryMock_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*courier.Courier))
	})
	return _c
}

func (_c *CourierRepositoryMock_Add_Call) Return(_a0 error) *CourierRepositoryMock_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CourierRepositoryMock_Add_Call) RunAndReturn(run func(context.Context, *courier.Courier) error) *CourierRepositoryMock_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, ID
func (_m *CourierRepositoryMock) Get(ctx context.Context, ID uuid.UUID) (*courier.Courier, error) {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *courier.Courier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*courier.Courier, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *courier.Courier); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*courier.Courier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CourierRepositoryMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CourierRepositoryMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *CourierRepositoryMock_Expecter) Get(ctx interface{}, ID interface{}) *CourierRepositoryMock_Get_Call {
	return &CourierRepositoryMock_Get_Call{Call: _e.mock.On("Get", ctx, ID)}
}

func (_c *CourierRepositoryMock_Get_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *CourierRepositoryMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *CourierRepositoryMock_Get_Call) Return(_a0 *courier.Courier, _a1 error) *CourierRepositoryMock_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CourierRepositoryMock_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*courier.Courier, error)) *CourierRepositoryMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllFree provides a mock function with given fields: ctx
func (_m *CourierRepositoryMock) GetAllFree(ctx context.Context) ([]*courier.Courier, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllFree")
	}

	var r0 []*courier.Courier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*courier.Courier, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*courier.Courier); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*courier.Courier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CourierRepositoryMock_GetAllFree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllFree'
type CourierRepositoryMock_GetAllFree_Call struct {
	*mock.Call
}

// GetAllFree is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CourierRepositoryMock_Expecter) GetAllFree(ctx interface{}) *CourierRepositoryMock_GetAllFree_Call {
	return &CourierRepositoryMock_GetAllFree_Call{Call: _e.mock.On("GetAllFree", ctx)}
}

func (_c *CourierRepositoryMock_GetAllFree_Call) Run(run func(ctx context.Context)) *CourierRepositoryMock_GetAllFree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CourierRepositoryMock_GetAllFree_Call) Return(_a0 []*courier.Courier, _a1 error) *CourierRepositoryMock_GetAllFree_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CourierRepositoryMock_GetAllFree_Call) RunAndReturn(run func(context.Context) ([]*courier.Courier, error)) *CourierRepositoryMock_GetAllFree_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, aggregate
func (_m *CourierRepositoryMock) Update(ctx context.Context, aggregate *courier.Courier) error {
	ret := _m.Called(ctx, aggregate)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *courier.Courier) error); ok {
		r0 = rf(ctx, aggregate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CourierRepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CourierRepositoryMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - aggregate *courier.Courier
func (_e *CourierRepositoryMock_Expecter) Update(ctx interface{}, aggregate interface{}) *CourierRepositoryMock_Update_Call {
	return &CourierRepositoryMock_Update_Call{Call: _e.mock.On("Update", ctx, aggregate)}
}

func (_c *CourierRepositoryMock_Update_Call) Run(run func(ctx context.Context, aggregate *courier.Courier)) *CourierRepositoryMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*courier.Courier))
	})
	return _c
}

func (_c *CourierRepositoryMock_Update_Call) Return(_a0 error) *CourierRepositoryMock_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CourierRepositoryMock_Update_Call) RunAndReturn(run func(context.Context, *courier.Courier) error) *CourierRepositoryMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewCourierRepositoryMock creates a new instance of CourierRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourierRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourierRepositoryMock {
	mock := &CourierRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
