// Code generated by mockery. DO NOT EDIT.

package portsmocks

import (
	context "context"
	ports "delivery/internal/core/ports"

	mock "github.com/stretchr/testify/mock"
)

// UnitOfWorkFactoryMock is an autogenerated mock type for the UnitOfWorkFactory type
type UnitOfWorkFactoryMock struct {
	mock.Mock
}

type UnitOfWorkFactoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UnitOfWorkFactoryMock) EXPECT() *UnitOfWorkFactoryMock_Expecter {
	return &UnitOfWorkFactoryMock_Expecter{mock: &_m.Mock}
}

// New provides a mock function with given fields: ctx
func (_m *UnitOfWorkFactoryMock) New(ctx context.Context) (ports.UnitOfWork, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 ports.UnitOfWork
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (ports.UnitOfWork, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) ports.UnitOfWork); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.UnitOfWork)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnitOfWorkFactoryMock_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type UnitOfWorkFactoryMock_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UnitOfWorkFactoryMock_Expecter) New(ctx interface{}) *UnitOfWorkFactoryMock_New_Call {
	return &UnitOfWorkFactoryMock_New_Call{Call: _e.mock.On("New", ctx)}
}

func (_c *UnitOfWorkFactoryMock_New_Call) Run(run func(ctx context.Context)) *UnitOfWorkFactoryMock_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UnitOfWorkFactoryMock_New_Call) Return(_a0 ports.UnitOfWork, _a1 error) *UnitOfWorkFactoryMock_New_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UnitOfWorkFactoryMock_New_Call) RunAndReturn(run func(context.Context) (ports.UnitOfWork, error)) *UnitOfWorkFactoryMock_New_Call {
	_c.Call.Return(run)
	return _c
}

// NewUnitOfWorkFactoryMock creates a new instance of UnitOfWorkFactoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnitOfWorkFactoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnitOfWorkFactoryMock {
	mock := &UnitOfWorkFactoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
